introduce env AMS_DATA

diff --git a/bin/supply b/bin/supply
--- a/bin/supply
+++ b/bin/supply
@@ -4,7 +4,7 @@
 set -euo pipefail
 
 BUILD_DIR=$1
-#CACHE_DIR=$2
+CACHE_DIR=$2
 DEPS_DIR=$3
 DEPS_IDX=$4
 
@@ -43,21 +43,35 @@ export opa_config=$rt_deps$config_file
 export log_level=$log_level 
 export OPA_URL=http://localhost:$opa_port/
 export OPA_PORT=$opa_port
+export ADC_URL=http://localhost:$opa_port/
 eof
 
 cat "$BUILD_DIR/.profile.d/0000_opa_env.sh"
 chmod +x "$BUILD_DIR/.profile.d/0000_opa_env.sh"
 
-if cas_files=$(find $BUILD_DIR$BUNDLE_PATH/cas -mindepth 1 ) ; then
-  echo "uploading cas folder with $cas_files"
-  if curl --fail --location --request POST "$(echo "$ams_creds" | jq -r '.url' )sap/cas/v1/bundles/SAP.tar.gz" --cert "$CF_INSTANCE_CERT" --key "$CF_INSTANCE_KEY" $(find $BUILD_DIR$BUNDLE_PATH/cas -mindepth 1 -printf "--form data=@%p ") ; then
-    echo "upload success"
-  else
-    curl --location --request POST "$(echo "$ams_creds" | jq -r '.url' )sap/cas/v1/bundles/SAP.tar.gz" --cert "$CF_INSTANCE_CERT" --key "$CF_INSTANCE_KEY" $(find $BUILD_DIR$BUNDLE_PATH/cas -mindepth 1 -printf "--form data=@%p ")
+if [[ -z "${AMS_DATA}" ]] ; then
+  >&2 echo "WARNING: This app will upload no authorization data"
+else
+  if ! ams_root=$(echo "$AMS_DATA" | jq -e -r '.root' ) ; then
+    >&2 echo "ERROR: Could not parse 'root' attribute from env variable AMS_DATA"
     exit 1
   fi
-else
-  >&2 echo "**WARNING** No cas folder found"
+  if ! ams_dirs=$(echo "$AMS_DATA" | jq -e -r '.directories[]' ) ; then
+    >&2 echo "ERROR: Could not parse 'directories' attribute from env variable AMS_DATA"
+    exit 1
+  fi
+  if ! echo "$AMS_DATA" | jq -e -r '.directories[0]' > /dev/null ; then
+    >&2 echo "ERROR: 'directories' attribute in env variable AMS_DATA must contain at least one string"
+    exit 1
+  fi
+
+  tar -vczf "$CACHE_DIR/auth.tar.gz" -C "$BUILD_DIR$ams_root" "$ams_dirs"
+
+  if ! curl --fail --location --header 'Content-Type: application/gzip' --request POST "$(echo "$ams_creds" | jq -r '.url' )sap/cas/v1/bundles/SAP.tar.gz" --cert "$CF_INSTANCE_CERT" --key "$CF_INSTANCE_KEY" --data-binary "@$CACHE_DIR/auth.tar.gz" ; then
+    curl --location --header 'Content-Type: application/gzip' --request POST "$(echo "$ams_creds" | jq -r '.url' )sap/cas/v1/bundles/SAP.tar.gz" --cert "$CF_INSTANCE_CERT" --key "$CF_INSTANCE_KEY" --data-binary "@$CACHE_DIR/auth.tar.gz"
+    exit 1
+  fi
+
 fi
  
 cat <<- eof > "$opa_config"
